## Numpy Array Operation

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])
print("Basic Slicing", arr[1:4])  # Slicing from index 1 to 3
print("Slicing with step", arr[0:6:2])  # Slicing with a step of 2
print("Slicing with negative indices", arr[-3:])  # Slicing from the third last element to the end

Basic Slicing [2 3 4]
Slicing with step [1 3 5]
Slicing with negative indices [4 5 6]


In [ ]:
arr_2d = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
print("Specific Element", arr_2d[1,2]) # Accessing element at row 1, column 2
print("entire Row", arr_2d[1,:]) # Accessing the entire second row
print("entire Column", arr_2d[:,2]) # Accessing the entire third column
print("Sub-array Slicing", arr_2d[0:2, 1:3])  # Slicing a sub-array from rows 0 to 1 and columns 1 to 2
print("Slicing with step in 2D", arr_2d[::2, ::2])  # Slicing every second row and column
print("Negative Indexing in 2D", arr_2d[-1, -1])  # Accessing the last element in the last row
print("Negative Row Slicing", arr_2d[-2:, :])  # Slicing the last two rows
print("Negative Column Slicing", arr_2d[:, -2:])  # Slicing the last two columns

## Sorting 


In [ ]:
unsorted = np.array([3,4,3,4,5])
print("Sorted Array", np.sort(unsorted))  # Sorting the array

arr_2d_unsorted = np.array([[3,4,3,4],
                            [2,3,4,5]])
print("Sorted 2D Array by Column", np.sort(arr_2d_unsorted, axis=0))  # Sorting the 2D array along the first axis (columns)
print("Sorted 2D Array by Row", np.sort(arr_2d_unsorted, axis=1))  # Sorting the 2D array along the second axis (rows)

## Filter


In [ ]:
numbers = np.array([1,2,3,4,5])
even_numbers = numbers[numbers % 2 == 0]  # Filtering even numbers
print("Filtered Even Numbers", even_numbers)  # Displaying the filtered even numbers

## Filter with mask

In [ ]:
numbers = np.array([1 , 2 ,3 ,4 ,5 ,6,7,8,9,10])
mask = numbers > 5  # mask is expression which evaluate value
print("Numbers greater than 5", numbers[mask])  # Displaying the filtered numbers

## Fancy indexing vs np.where()

In [ ]:
indices = [0,1,2,2] # Indices to access specific elements
print(numbers[indices])


where_indices = np.where(numbers > 5)  # Getting indices where condition is true
print("np where result", where_indices)  # Displaying the indices



condition = np.where(numbers > 5 , numbers * 2 , numbers)
# Applying a condition to modify elements based on a condition
print(condition)

condition = np.where(numbers > 5 , "true", "false")
# Applying a condition to modify elements based on a condition, where modify existing values
print(condition)


[1 2 3 3]
np where result (array([5, 6, 7, 8, 9]),)
[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing Data

In [ ]:
arr1 = np.array([2,3,4,4])
arr2 = np.array([1, 2, 3])

combined = np.concatenate((arr1, arr2))  # Concatenating two arrays
print(combined)


In [ ]:
arr = np.array([1 ,2 ,3 , 4 ,5])
deleted = np.delete(arr, 2 ) # Deleting an element at index 2
print(deleted)

[1 2 4 5]


## Array Compatibility

In [ ]:
a = np.array([1 , 2, 3])
b = np.array([4 , 5, 6 ])
c = np.array([7 , 8,  9])
print("Compatibility : " , a.shape == b.shape)

In [ ]:
original = np.array([[1, 2, 3],[3,4,5]])
new_row = np.array([[5 ,6]])
with_new_row = np.vstack((original , new_row)) # vertical stack add new row to the original array
print(with_new_row)



new_col = np.array([[7] , [8]])
with_new_col = np.hstack((original , new_col))# horizontal stack add new column to the original array
print(with_new_col)